lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "reflect"
rust-version.workspace = true
version.workspace = true

[features]
alloc = []
default = ["std"]
nightly = []
std = ["alloc"]
