lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_binary"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, default-features = false }
tap.workspace = true

[dev-dependencies]
serde_bytes = { path = "../serde_bytes", default-features = false, features = [
    "alloc"
] }
serde_derive = "1"
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[features]
alloc = ["serde/alloc"]
default = ["std"]
std = ["alloc", "serde/std"]
