lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_semantic"
rust-version.workspace = true
version.workspace = true

[dependencies]
hashbrown = { version = "0.15", default-features = false, features = [
    "alloc",
    "default-hasher",
    "equivalent",
    "serde"
] }
nom_locate = { version = "5", default-features = false, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = [
    "alloc",
    "derive"
] }
tap.workspace = true

[features]
default = ["std"]
std = ["nom_locate/std", "serde/std"]
