lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_semantic"
rust-version.workspace = true
version.workspace = true

[dependencies]
key-node-list = "0.0.5"
