lib.proc-macro = true
lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_ident_macros"
rust-version.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["parsing"] }
