lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_reflect"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["serde/std"]
