lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm-value"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
vmm-length = { path = "../length", default-features = false }
vmm-var-num.workspace = true

[features]
default = ["std"]
serde = ["dep:serde"]
std = ["vmm-length/std", "vmm-var-num/std"]
