lib.proc-macro = true
lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_derive"
rust-version.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
