lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_intern"
rust-version.workspace = true
version.workspace = true

[dependencies]
parking_lot = "0.12.4"

[dev-dependencies]
criterion = "0.6"
quickcheck = "1.0.3"

[[bench]]
name = "basic"
harness = false
