lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_bytes"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, default-features = false }

[features]
alloc = ["serde/alloc"]
default = ["std"]
std = ["alloc", "serde/std"]
