lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_span"
rust-version.workspace = true
version.workspace = true

[dependencies]
rayon.workspace = true
serde.workspace = true
vmm_num.workspace = true
