lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_alloc"
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]
nightly = []
std = []
