lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_nbt"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = "1"
thiserror = "2"
bytes = "1"
cesu8 = "1.1"
