lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_par_gc"
rust-version.workspace = true
version.workspace = true

[dependencies]
vmm_par_utils = { path = "../utils", default-features = false }

[features]
alloc = []
default = ["std"]
std = ["alloc", "vmm_par_utils/std"]
