lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_opt"
rust-version.workspace = true
version.workspace = true

[dependencies]
itertools = "0.14"
ron = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "std"] }
serde-value = "0.7.0"
serde_array.workspace = true
tap = "1"
tracing = "0.1"
vmm_ir.workspace = true
vmm_num.workspace = true
vmm_program.workspace = true
vmm_span.workspace = true
vmm_tape.workspace = true
vmm_type_name = { path = "../type_name" }
vmm_utils = { workspace = true, features = ["get_or_zero", "insert_or_push"] }
vmm_vec = { path = "../vec", features = ["nightly"] }

[features]
output = ["dep:ron"]
