lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_opt"
rust-version.workspace = true
version.workspace = true

[dependencies]
bitflags = "2.9.0"
ron = { version = "0.10", optional = true }
serde = { workspace = true, features = ["derive", "std"] }
serde-value = "0.7.0"
serde_array.workspace = true
tracing = "0.1"
vmm_ir.workspace = true
vmm_program.workspace = true
vmm_tape.workspace = true
vmm_utils = { path = "../utils" }

[features]
output-metadata = ["dep:ron"]
