lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm-aux"
rust-version.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true
vmm = { path = "../../" }
vmm-tools = { path = "../tools" }
