lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_utils"
rust-version.workspace = true
version.workspace = true

[features]
alloc = []
get_or_zero = []
heap_size = ["alloc"]
insert_or_push = ["alloc"]
span = []
