lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm-tools"
rust-version.workspace = true
version.workspace = true

[dependencies]
customasm = "^0.13.7"
thiserror = "2.0.11"
vmm = { path = "../../" }
