lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_redpiler"
rust-version.workspace = true
version.workspace = true

[dependencies]
enum_dispatch = "0.3"
itertools = "0.14"
parking_lot = "0.12"
petgraph = "0.8"
rustc-hash.workspace = true
serde_json.workspace = true
tracing.workspace = true
vmm_blocks.workspace = true
vmm_redpiler_graph = { path = "../redpiler_graph" }
vmm_redstone = { path = "../redstone" }
vmm_world.workspace = true
