lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_redpiler"
rust-version.workspace = true
version.workspace = true

[dependencies]
vmm_redpiler_graph = { path = "../redpiler_graph" }
serde_json.workspace = true
tracing.workspace = true
petgraph = "0.8"
itertools = "0.14"
rustc-hash.workspace = true
parking_lot = "0.12"
