lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_tape"
rust-version.workspace = true
version.workspace = true

[dependencies]
rayon = { version = "1", default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_array.workspace = true
vmm_num.workspace = true
vmm_utils = { workspace = true, features = ["get_or_zero"] }
