lib.proc-macro = true
lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_protocol_macros"
rust-version.workspace = true
version.workspace = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
