lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "koopa_playground"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.98"
clap = { version = "4", features = ["derive"] }
koopa = "0.0.8"
