lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_text"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid = { workspace = true, features = ["serde"] }
vmm_ident.workspace = true
vmm_nbt = { path = "../nbt" }

[dev-dependencies]
anyhow.workspace = true
