lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_text"
rust-version.workspace = true
version.workspace = true

[dependencies]
once_cell = "1"
regex = "1"
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
