lints.workspace = true

[package]
build = "build/main.rs"
edition.workspace = true
license.workspace = true
name = "vmm_generated"
rust-version.workspace = true
version.workspace = true

[dependencies]
uuid.workspace = true
vmm_ident.workspace = true
vmm_math = { path = "../math" }

[build-dependencies]
anyhow.workspace = true
heck = "0.5"
proc-macro2.workspace = true
quote = "1"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
vmm_alloc = { path = "../alloc" }
vmm_build_utils = { path = "../build_utils" }
