lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_protocol"
rust-version.workspace = true
version.workspace = true

[dependencies]
aes = { version = "0.8", optional = true }
anyhow.workspace = true
base64 = "0.22"
bevy_ecs = { workspace = true, default-features = false }
bitfield-struct = "0.10"
byteorder.workspace = true
bytes = "1"
cfb8 = { version = "0.8", optional = true }
flate2 = { version = "1.1", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing = "0.1"
url = "2"
uuid.workspace = true
vmm_generated = { path = "../generated" }
vmm_ident.workspace = true
vmm_math.workspace = true
vmm_nbt = { workspace = true, features = ["binary"] }
vmm_protocol_macros = { path = "../protocol_macros" }
vmm_text = { path = "../text" }

[dev-dependencies]
rand = "0.9"

[features]
compression = ["dep:flate2"]
encryption = ["dep:aes", "dep:cfb8"]
