lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm-var-num"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
thiserror = { version = "2", default-features = false }

[features]
default = ["serde", "std"]
serde = ["dep:serde"]
std = ["serde?/std", "thiserror/std"]
