lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_build_utils"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
proc-macro2.workspace = true
syn.workspace = true
