lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "sys-util"
rust-version.workspace = true
version.workspace = true

[dependencies]
libc = "0.2.39"
serde = { version = "1", optional = true, features = ["derive"] }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
bitflags = "2.8"

[features]
serde = ["dep:serde"]
