lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_spatial"
rust-version.workspace = true
version.workspace = true

[dependencies]
approx = "0.5"
rayon = "1"
vek = "0.17"
