lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_vec"
rust-version.workspace = true
version.workspace = true

[features]
nightly = []
std = []

[dependencies]
bytes = { version = "1", optional = true, default-features = false }
serde = { workspace = true, default-features = false }
vmm_utils = { workspace = true, features = ["insert_or_push"] }

[dev-dependencies]
criterion = "0.6"

[[bench]]
harness = false
name = "bench"
