lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_stack"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["std"] }
stacker = "0.1"

[dev-dependencies]
serde_json = { workspace = true, features = ["unbounded_depth"] }
