lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_stack"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["std"] }
# stacker = { git = "https://github.com/rust-lang/stacker.git" }

[target.'cfg(not(miri))'.dependencies]
stacker = { git = "https://github.com/rust-lang/stacker.git" }

[dev-dependencies]
serde_json = { workspace = true, features = ["unbounded_depth"] }
