lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "serde_array"
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, default-features = false }

[dev-dependencies]
anyhow = "1"
serde = { workspace = true, default-features = true, features = ["derive"] }
serde-value = "0.7.0"
serde_json.workspace = true
