lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_redpiler_graph"
rust-version.workspace = true
version.workspace = true

[dependencies]
bincode = "1.3"
serde = { workspace = true, features = ["derive"] }
