lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_testing"
rust-version.workspace = true
version.workspace = true

[dependencies]
arbitrary.workspace = true
