lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "erased_discriminant"
rust-version.workspace = true
version.workspace = true

[dependencies]
typeid.workspace = true
