lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_type_name"
rust-version.workspace = true
version.workspace = true

[features]
default = ["alloc"]
alloc = []
