lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "vmm_par_iter"
rust-version.workspace = true
version.workspace = true

[dependencies]
rayon-core = { version = "1.12" }
vmm_num.workspace = true
vmm_span.workspace = true
